# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a28fa80e8d630672449982223729aa43c3f2c3e41ef12d3af77df4182cfd9c111aa4635aa37c67e08cb0f6c76b3ccf183c7dbad039fa5f0329000788d302b4b9

test:
  secret_key_base: 34131439fc656312d1f7eac3ef7817edcbcbda7991e271d6af41e86f54dfcf7caf03b5d8df167c49f6bf3c53e5a5d6f58325c76bc40676de8df337bdf29bb007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
